version: '3'

services:
    flask:
      build: ./
      ports: [
        5000
      ]
      networks:
        - to-do-flask_network

    nginx:
      image: nginx:latest
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
      - flask
      ports: [
        "80:80"
      ]
      networks:
        - to-do-flask_network

networks:
  to-do-flask_network:
    driver: bridge